receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  hostmetrics:
    collection_interval: 15s
    root_path: /hostfs
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    collection_interval: 15s
    container_labels_to_metric_labels:
      com.docker.compose.service: container_service

processors:
  batch:

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  otlp_http/tempo:
    endpoint: http://tempo:4318

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    metrics/app:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    metrics/host:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [prometheus]
    metrics/docker:
      receivers: [docker_stats]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/tempo]
